- name: Start all the IdP related services
  service:
    name: "{{ item }}"
    state: started
  with_items:
    - jetty
    - mysql
    - slapd

- name: Enable the Apache2 idp.conf
  shell: "mv /etc/apache2/conf-enabled/idp.conf.org /etc/apache2/conf-enabled/idp.conf"
  notify:
    - Restart Apache2

- name: Disable the Apache2 maintenance config file
  shell: "a2disconf maintenance"
  notify:
    - Restart Apache2



  