- name: Look for ldap-backup script
  stat:
    path: /ect/cron.hourly/ldap-backup
  register: ldapbackup

- name: Start Jetty
  service:
    name: jetty
    state: started

- name: Start Mysql
  service:
    name: mysql
    state: started

- name: Started Openldap
  service:
    name: slapd
    state: started
  when: ldapbackup.stat.exists is defined

- name: Enable the Apache2 idp.conf
  shell: "mv /etc/apache2/conf-enabled/idp.conf.org /etc/apache2/conf-enabled/idp.conf"
  notify:
    - Restart Apache2

- name: Disable the Apache2 maintenance config file
  shell: "a2disconf maintenance"
  notify:
    - Restart Apache2



  